import { UserNav } from '@/components/user-nav'
import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("container", inter.className)}>
        <div className="flex items-center justify-between py-4 space-y-2">
          <h2 className="text-2xl font-bold tracking-tight">Anilist Activity Scheduler</h2>
          <div className="flex items-center space-x-2">
            <UserNav loggedIn={false} />
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
