import { UserNav } from '@/components/user-nav'
import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={cn("!m-0", inter.className)}>
        <div className="container">
          <header className="flex items-center justify-between py-4 space-y-2">
            <Link className="text-2xl font-bold tracking-tight" href="/">Anilist Activity Scheduler</Link>
            <div className="flex items-center space-x-8">
              <Link href="/templates" className='font-semibold'>Templates</Link>
              <UserNav loggedIn={!!session?.user} userData={session?.user} />
            </div>
          </header>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
