import { LoginButton } from "@/components/login-button";
import { cn } from "@/lib/utils";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  // if (session) {
  //   prismaClient.user.create({
  //     data: session.user
  //   })
  // }

  return (
    <html lang="en">
      <body className={cn("!m-0", inter.className)}>
        <div className="container">
          <header className="flex items-center justify-between py-4 space-y-2">
            <Link className="text-2xl font-bold tracking-tight" href="/">
              Anilist Activity Scheduler
            </Link>
            {session ? (
              <div className="flex items-center space-x-8">
                <Link href="/templates" className="font-semibold">
                  Templates
                </Link>
                <LoginButton loggedIn={!!session?.user} userData={session?.user} />
              </div>
            ) : null}
          </header>
          <main>
            {session ? <>{children}</> : <LoginButton loggedIn={false} />}
          </main>
        </div>
      </body>
    </html>
  );
}
